"""One-off script to load sample menu docs (PRD Section 13) into MongoDB.

Usage (once MONGODB_URI is set in .env):
    python scripts/seed_menu.py
"""

import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app import create_app
from app.models.db import ensure_indexes, get_db

SAMPLE_MENU = [
    # Starters
    {
        "item_id": "paneer-tikka",
        "name": "Paneer Tikka",
        "description": "Char-grilled marinated cottage cheese.",
        "category": "Starter",
        "price": 180,
        "availability": True,
        "is_veg": True,
        "image": None,
        "tags": ["vegetarian", "starter", "spicy"],
        "active": True,
    },
    {
        "item_id": "chicken-tikka",
        "name": "Chicken Tikka",
        "description": "Char-grilled marinated chicken skewers.",
        "category": "Starter",
        "price": 220,
        "availability": True,
        "is_veg": False,
        "image": None,
        "tags": ["chicken", "starter", "spicy"],
        "active": True,
    },
    # Main Course
    {
        "item_id": "chicken-biryani",
        "name": "Chicken Biryani",
        "description": "Fragrant basmati rice layered with spiced chicken.",
        "category": "Main Course",
        "price": 280,
        "availability": True,
        "is_veg": False,
        "image": None,
        "tags": ["chicken", "rice", "spicy"],
        "active": True,
    },
    {
        "item_id": "veg-biryani",
        "name": "Veg Biryani",
        "description": "Fragrant basmati rice layered with mixed vegetables.",
        "category": "Main Course",
        "price": 220,
        "availability": True,
        "is_veg": True,
        "image": None,
        "tags": ["vegetarian", "rice"],
        "active": True,
    },
    # Burgers
    {
        "item_id": "veg-burger",
        "name": "Veg Burger",
        "description": "Classic vegetable patty burger.",
        "category": "Burger",
        "price": 150,
        "availability": True,
        "is_veg": True,
        "image": None,
        "tags": ["vegetarian", "burger"],
        "active": True,
    },
    {
        "item_id": "chicken-burger",
        "name": "Chicken Burger",
        "description": "Grilled chicken patty burger.",
        "category": "Burger",
        "price": 220,
        "availability": False,
        "is_veg": False,
        "image": None,
        "tags": ["chicken", "burger"],
        "active": True,
    },
    # Wraps -- alternatives for the unavailable Chicken Burger (PRD Section 18 example)
    {
        "item_id": "chicken-wrap",
        "name": "Chicken Wrap",
        "description": "Grilled chicken and salad rolled in a soft tortilla.",
        "category": "Wrap",
        "price": 190,
        "availability": True,
        "is_veg": False,
        "image": None,
        "tags": ["chicken", "wrap"],
        "active": True,
    },
    {
        "item_id": "chicken-roll",
        "name": "Chicken Roll",
        "description": "Spiced chicken and onions rolled in a paratha.",
        "category": "Wrap",
        "price": 170,
        "availability": True,
        "is_veg": False,
        "image": None,
        "tags": ["chicken", "wrap", "spicy"],
        "active": True,
    },
    # Beverages
    {
        "item_id": "coke",
        "name": "Coke",
        "description": "Chilled soft drink.",
        "category": "Beverage",
        "price": 60,
        "availability": True,
        "is_veg": True,
        "image": None,
        "tags": ["drink"],
        "active": True,
    },
    {
        "item_id": "fresh-lime",
        "name": "Fresh Lime",
        "description": "Freshly squeezed lime soda.",
        "category": "Beverage",
        "price": 80,
        "availability": True,
        "is_veg": True,
        "image": None,
        "tags": ["drink"],
        "active": True,
    },
    # Dessert
    {
        "item_id": "gulab-jamun",
        "name": "Gulab Jamun",
        "description": "Warm milk-solid dumplings soaked in sugar syrup.",
        "category": "Dessert",
        "price": 90,
        "availability": True,
        "is_veg": True,
        "image": None,
        "tags": ["dessert", "sweet"],
        "active": True,
    },
    # --- 30 additional items, added across the existing 6 categories ---
    # More Starters
    {
        "item_id": "veg-spring-roll",
        "name": "Veg Spring Roll",
        "description": "Crispy rolls stuffed with spiced mixed vegetables.",
        "category": "Starter",
        "price": 160,
        "availability": True,
        "is_veg": True,
        "image": None,
        "tags": ["vegetarian", "starter", "fried"],
        "active": True,
    },
    {
        "item_id": "chicken-65",
        "name": "Chicken 65",
        "description": "Deep-fried spicy chicken bites tempered with curry leaves.",
        "category": "Starter",
        "price": 240,
        "availability": True,
        "is_veg": False,
        "image": None,
        "tags": ["chicken", "starter", "spicy"],
        "active": True,
    },
    {
        "item_id": "fish-amritsari",
        "name": "Fish Amritsari",
        "description": "Batter-fried fish fillets with a tangy Punjabi spice coating.",
        "category": "Starter",
        "price": 260,
        "availability": True,
        "is_veg": False,
        "image": None,
        "tags": ["fish", "starter", "fried"],
        "active": True,
    },
    {
        "item_id": "hara-bhara-kebab",
        "name": "Hara Bhara Kebab",
        "description": "Pan-seared patties of spinach, peas, and potato.",
        "category": "Starter",
        "price": 170,
        "availability": True,
        "is_veg": True,
        "image": None,
        "tags": ["vegetarian", "starter"],
        "active": True,
    },
    {
        "item_id": "chilli-chicken",
        "name": "Chilli Chicken",
        "description": "Indo-Chinese stir-fried chicken tossed in chilli-soy sauce.",
        "category": "Starter",
        "price": 250,
        "availability": True,
        "is_veg": False,
        "image": None,
        "tags": ["chicken", "starter", "spicy", "indo-chinese"],
        "active": True,
    },
    # More Main Course
    {
        "item_id": "butter-chicken",
        "name": "Butter Chicken",
        "description": "Tandoori chicken simmered in a creamy tomato-butter gravy.",
        "category": "Main Course",
        "price": 320,
        "availability": True,
        "is_veg": False,
        "image": None,
        "tags": ["chicken", "gravy", "creamy"],
        "active": True,
    },
    {
        "item_id": "paneer-butter-masala",
        "name": "Paneer Butter Masala",
        "description": "Cottage cheese cubes in a rich buttery tomato gravy.",
        "category": "Main Course",
        "price": 260,
        "availability": True,
        "is_veg": True,
        "image": None,
        "tags": ["vegetarian", "paneer", "gravy"],
        "active": True,
    },
    {
        "item_id": "dal-makhani",
        "name": "Dal Makhani",
        "description": "Slow-cooked black lentils finished with cream and butter.",
        "category": "Main Course",
        "price": 220,
        "availability": True,
        "is_veg": True,
        "image": None,
        "tags": ["vegetarian", "dal", "gravy"],
        "active": True,
    },
    {
        "item_id": "mutton-rogan-josh",
        "name": "Mutton Rogan Josh",
        "description": "Tender mutton simmered in a deep red Kashmiri chilli gravy.",
        "category": "Main Course",
        "price": 380,
        "availability": True,
        "is_veg": False,
        "image": None,
        "tags": ["mutton", "gravy", "spicy"],
        "active": True,
    },
    {
        "item_id": "kadai-paneer",
        "name": "Kadai Paneer",
        "description": "Paneer and bell peppers tossed in a coarsely ground spice masala.",
        "category": "Main Course",
        "price": 250,
        "availability": True,
        "is_veg": True,
        "image": None,
        "tags": ["vegetarian", "paneer", "gravy"],
        "active": True,
    },
    # More Burgers
    {
        "item_id": "cheese-burger",
        "name": "Cheese Burger",
        "description": "Classic veg patty burger loaded with melted cheese.",
        "category": "Burger",
        "price": 170,
        "availability": True,
        "is_veg": True,
        "image": None,
        "tags": ["vegetarian", "burger", "cheese"],
        "active": True,
    },
    {
        "item_id": "double-chicken-burger",
        "name": "Double Chicken Burger",
        "description": "Two grilled chicken patties stacked with lettuce and mayo.",
        "category": "Burger",
        "price": 260,
        "availability": True,
        "is_veg": False,
        "image": None,
        "tags": ["chicken", "burger"],
        "active": True,
    },
    {
        "item_id": "mushroom-burger",
        "name": "Mushroom Burger",
        "description": "Grilled mushroom and cheese patty burger.",
        "category": "Burger",
        "price": 180,
        "availability": True,
        "is_veg": True,
        "image": None,
        "tags": ["vegetarian", "burger", "mushroom"],
        "active": True,
    },
    {
        "item_id": "fish-burger",
        "name": "Fish Burger",
        "description": "Crispy fried fish fillet burger with tartar sauce.",
        "category": "Burger",
        "price": 230,
        "availability": True,
        "is_veg": False,
        "image": None,
        "tags": ["fish", "burger"],
        "active": True,
    },
    {
        "item_id": "paneer-burger",
        "name": "Paneer Burger",
        "description": "Spiced grilled paneer patty burger.",
        "category": "Burger",
        "price": 190,
        "availability": True,
        "is_veg": True,
        "image": None,
        "tags": ["vegetarian", "burger", "paneer"],
        "active": True,
    },
    # More Wraps
    {
        "item_id": "veg-wrap",
        "name": "Veg Wrap",
        "description": "Grilled mixed vegetables and salad rolled in a soft tortilla.",
        "category": "Wrap",
        "price": 160,
        "availability": True,
        "is_veg": True,
        "image": None,
        "tags": ["vegetarian", "wrap"],
        "active": True,
    },
    {
        "item_id": "paneer-roll",
        "name": "Paneer Roll",
        "description": "Spiced paneer tikka and onions rolled in a paratha.",
        "category": "Wrap",
        "price": 180,
        "availability": True,
        "is_veg": True,
        "image": None,
        "tags": ["vegetarian", "wrap", "paneer"],
        "active": True,
    },
    {
        "item_id": "egg-roll",
        "name": "Egg Roll",
        "description": "Fried egg and spiced onions rolled in a paratha.",
        "category": "Wrap",
        "price": 150,
        "availability": True,
        "is_veg": False,
        "image": None,
        "tags": ["egg", "wrap"],
        "active": True,
    },
    {
        "item_id": "mutton-seekh-roll",
        "name": "Mutton Seekh Roll",
        "description": "Minced mutton kebab rolled in a soft paratha.",
        "category": "Wrap",
        "price": 220,
        "availability": True,
        "is_veg": False,
        "image": None,
        "tags": ["mutton", "wrap", "spicy"],
        "active": True,
    },
    {
        "item_id": "falafel-wrap",
        "name": "Falafel Wrap",
        "description": "Crispy falafel, hummus, and salad in a soft wrap.",
        "category": "Wrap",
        "price": 190,
        "availability": True,
        "is_veg": True,
        "image": None,
        "tags": ["vegetarian", "wrap"],
        "active": True,
    },
    # More Beverages
    {
        "item_id": "masala-chai",
        "name": "Masala Chai",
        "description": "Spiced Indian milk tea brewed with cardamom and ginger.",
        "category": "Beverage",
        "price": 40,
        "availability": True,
        "is_veg": True,
        "image": None,
        "tags": ["drink", "hot"],
        "active": True,
    },
    {
        "item_id": "cold-coffee",
        "name": "Cold Coffee",
        "description": "Chilled blended coffee with milk and ice cream.",
        "category": "Beverage",
        "price": 90,
        "availability": True,
        "is_veg": True,
        "image": None,
        "tags": ["drink", "cold"],
        "active": True,
    },
    {
        "item_id": "mango-lassi",
        "name": "Mango Lassi",
        "description": "Thick yogurt smoothie blended with sweet mango pulp.",
        "category": "Beverage",
        "price": 100,
        "availability": True,
        "is_veg": True,
        "image": None,
        "tags": ["drink", "cold"],
        "active": True,
    },
    {
        "item_id": "orange-juice",
        "name": "Orange Juice",
        "description": "Freshly squeezed orange juice.",
        "category": "Beverage",
        "price": 90,
        "availability": True,
        "is_veg": True,
        "image": None,
        "tags": ["drink", "cold"],
        "active": True,
    },
    {
        "item_id": "buttermilk",
        "name": "Buttermilk (Chaas)",
        "description": "Spiced, churned yogurt drink.",
        "category": "Beverage",
        "price": 50,
        "availability": True,
        "is_veg": True,
        "image": None,
        "tags": ["drink", "cold"],
        "active": True,
    },
    # More Desserts
    {
        "item_id": "rasgulla",
        "name": "Rasgulla",
        "description": "Soft cottage-cheese balls soaked in light sugar syrup.",
        "category": "Dessert",
        "price": 80,
        "availability": True,
        "is_veg": True,
        "image": None,
        "tags": ["dessert", "sweet"],
        "active": True,
    },
    {
        "item_id": "kheer",
        "name": "Kheer",
        "description": "Creamy rice pudding simmered with milk and cardamom.",
        "category": "Dessert",
        "price": 90,
        "availability": True,
        "is_veg": True,
        "image": None,
        "tags": ["dessert", "sweet"],
        "active": True,
    },
    {
        "item_id": "ice-cream",
        "name": "Ice Cream",
        "description": "Choice of vanilla, chocolate, or strawberry scoop.",
        "category": "Dessert",
        "price": 70,
        "availability": True,
        "is_veg": True,
        "image": None,
        "tags": ["dessert", "cold"],
        "active": True,
    },
    {
        "item_id": "chocolate-brownie",
        "name": "Chocolate Brownie",
        "description": "Warm fudgy brownie served with a scoop of ice cream.",
        "category": "Dessert",
        "price": 120,
        "availability": True,
        "is_veg": True,
        "image": None,
        "tags": ["dessert", "sweet"],
        "active": True,
    },
    {
        "item_id": "rasmalai",
        "name": "Rasmalai",
        "description": "Soft paneer discs soaked in saffron-cardamom milk.",
        "category": "Dessert",
        "price": 100,
        "availability": True,
        "is_veg": True,
        "image": None,
        "tags": ["dessert", "sweet"],
        "active": True,
    },
]


def main():
    app = create_app()
    with app.app_context():
        db = get_db()
        ensure_indexes(db)

        now = datetime.now(timezone.utc)
        for item in SAMPLE_MENU:
            db.menu.update_one(
                {"item_id": item["item_id"]},
                {"$set": {**item, "updated_at": now}, "$setOnInsert": {"created_at": now}},
                upsert=True,
            )

        print(f"Seeded {len(SAMPLE_MENU)} menu items.")


if __name__ == "__main__":
    main()
